apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: velero-backup-config
    envs:
    - .env

replacements:
  - source:
      name: velero-backup-config
      kind: ConfigMap
      fieldPath: data.MINIOS3_ENDPOINT
    targets:
    - select:
        kind: HelmRelease
      fieldPaths:
      - spec.values.configuration.backupStorageLocation.0.config.s3Url
      - spec.values.configuration.backupStorageLocation.0.config.publicUrl
      - spec.values.configuration.volumeSnapshotLocation.0.config.s3Url
      - spec.values.configuration.volumeSnapshotLocation.0.config.publicUrl      
