---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
      interval: 60m
  values:
    snapshotsEnabled: true
    deployNodeAgent: true
    backupsEnabled: true
    resources:
      requests:
        cpu: 10m
        memory: 70Mi
      limits:
        cpu: 100m
        memory: 400Mi
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      podSecurityContext:
        runAsUser: 0
        fsGroup: 0
      resources:
        requests:
          cpu: 2m
          memory: 50Mi
        limits:
          cpu: 30m
          memory: 200Mi
    configuration:
      features: EnableCSI
      logLevel: debug
      uploaderType: kopia
      defaultSnapshotMoveData: false
      defaultVolumesToFsBackup: false
      backupStorageLocation:
      - provider: aws
        bucket: velero-backups
        name: default
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: to-be-replaced-by-config
          publicUrl: to-be-replaced-by-config
      volumeSnapshotLocation:
      - provider: nfs.csi.k8s.io
        name: default
        config:
          region: us-east-1
          bucket: velero-backups
          provider: aws
          s3ForcePathStyle: true
          s3Url: to-be-replaced-by-config
          publicUrl: to-be-replaced-by-config
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.0
      volumeMounts:
      - mountPath: /target
        name: plugins
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.6.3
      volumeMounts:
      - mountPath: /target
        name: plugins
    credentials:
      useSecret: true
      existingSecret: velero-minio-access
