persistence:
  # since we only have one node, we can have only 1 replica
  defaultClassReplicaCount: 2

defaultSettings:
  # This tells Longhorn to use the 'longhorn' bucket of our S3.
  # backupTarget: s3://longhorn@dummyregion/
  backupTarget: s3://longhorn@us-east-1/backupstore
  # The secret where the MinIO credentials are stored.
  backupTargetCredentialSecret: minio-secret
  # Usually Longhorn does not store volumes on the node that it runs on. This setting allows that.
  replicaSoftAntiAffinity: true
  replicaZoneSoftAntiAffinity: true
  defaultReplicaCount: 1
  createDefaultDiskLabeledNodes: true  # nodes with the label "node.longhorn.io/create-default-disk=true"
  defaultDataPath: /var/lib/longhorn/
longhornUI:
  replicas: 1
ingress:
  enabled: true

