apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
# The following values are base64-encoded.
# If you'd like to change them, you can encode your own values like this:
# echo -n "<your-value>" | base64
data:
  AWS_ACCESS_KEY_ID: CwBcv3ddyUqBWhJHzmfx # test-key
  AWS_SECRET_ACCESS_KEY: ueKA0UF0QFO0076MQ1CB4MOik0yYKWbmhgCB1sx3 # test-secret-key
  AWS_ENDPOINTS: aHR0cHM6Ly9taW5pby1zMy5kZXYuY29tcGxpYW50Y2xvdWQuY29t # http://172.17.0.1:9000