apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-data
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: nginx-data
    namespace: default
