---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: atreview-client-stub-mssql
  name: mssql-pvc
spec:
  storageClassName: longhorn-crypto-global
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

