---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc-enc
spec:
  storageClassName: longhorn-crypto-global
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

