apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    velero-backup-target: velero-dev-backup
  name: nginx-test-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        velero-backup-target: velero-dev-backup
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: nginx-data
          mountPath: /mydata
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: csi-nginx-data-test
