apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sentry
  name: nginx-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: longhorn
  volumeMode: Filesystem