apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
    velero-backup-target: velero-dev-backup-test
  name: nginx-data-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-path
  volumeMode: Filesystem
