apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
    velero-backup-target: velero-dev-backup-test
  name: sentry-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  # storageClassName: 
  storageClassName: nfs-client
  volumeMode: Filesystem
