apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
    velero-backup-target: velero-dev-backup-test
  name: csi-nginx-data-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  # storageClassName: 
  storageClassName: csi-nfs-client
  volumeMode: Filesystem
