apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sentry
  name: nginx-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem