apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  containers:
  - image: busybox
    name: busy
    resources: {}
    # command: ["/bin/sh", "-c", "while true; do echo $(date) > /storage/$(date); sleep 15;  done"]
    command: ["/bin/sh", "-c", "echo $(date) > /storage/$(date); sleep 3600;"]
    volumeMounts:
    - name: storage
      mountPath: /storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: mssql-pvc-enc
status: {}
