apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-from-snapshot
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: nginx-data-from-snapshot-content
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: nginx-data-from-snapshot-content
  resources:
    requests:
      storage: 200Mi
  storageClassName: csi-nfs-client
  volumeMode: Filesystem
