apiVersion: v1
data:
  # old_storage_class_name: new_storage_class_name # exp: ssd:premium like this
  longhorn: nfs-client
kind: ConfigMap
metadata:
  labels:
    velero.io/change-storage-class: RestoreItemAction
    velero.io/plugin-config: ""
  name: storage-class-config
  namespace: velero