apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.25.4
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "25"
  labels:
    velero.io/storage-location: default
  name: dev-backup-confirm-2
  namespace: velero
  resourceVersion: "3987"
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - '*'
  itemOperationTimeout: 4h0m0s
  labelSelector:
    matchLabels:
      velero-backup-target: velero-dev-backup-test
  metadata: {}
  snapshotMoveData: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
