kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: csi-hostpath-snapclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
# driver: hostpath.csi.k8s.io
driver: rancher.io/local-path
deletionPolicy: Delete
parameters:
  type: bak