kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: csi-nfs-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
# driver: hostpath.csi.k8s.io
driver: nfs.csi.k8s.io
deletionPolicy: Delete
# parameters:
#   type: snap
