apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nginx-data-snapshotcontent
spec:
  # driver: driver.longhorn.io
  driver: nfs.csi.k8s.io
  source:
    snapshotHandle: e2c83ce5-f0be-46b7-bdc9-e9ce7202599a
    # volumeHandle: pvc-2f163a00-89f3-4951-911e-2a9ac68005fa
  deletionPolicy: Delete
  sourceVolumeMode: Filesystem
  volumeSnapshotClassName: csi-nfs-snapclass
  volumeSnapshotRef:
    name: nginx-data-from-snapshot-content
    namespace: dev-tutug
