apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nginx-data-from-snapshot-content
spec:
  source:
    # volumeSnapshotContentName: nginx-data-snapshotcontent # This
    persistentVolumeClaimName: csi-nginx-data-test
  volumeSnapshotClassName: csi-nfs-snapclass
