apiVersion: batch/v1
kind: Job
metadata:
  name: copy-data-to-temp-pvc-dest
spec:
  template:
    spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: backup-copy
        command: ["/bin/bash", "-c", "cp -r /tmp/source/* /tmp/destination/; ls -al /tmp/destination/; rm -rf /tmp/source/*"]
        volumeMounts:
          - name: destination
            mountPath: /tmp/destination
          - name: source
            mountPath: /tmp/source/
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: temporary-pvc
        - name: destination
          persistentVolumeClaim:
            claimName: PVC_NAME
