apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: persistent-volume-backup-dev
  namespace: velero
spec:
  schedule: '*/15 * * * *'
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
    - '*'
    itemOperationTimeout: 0s
    labelSelector:
      matchLabels:
        velero-backup-target: velero-backup-dev
    metadata: {}
    snapshotMoveData: true
    ttl: 0s
  useOwnerReferencesInBackup: false
