apiVersion: batch/v1
kind: Job
metadata:
  name: copy-data-to-temp-pvc
spec:
  template:
    spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: backup-copy
        command: ["/bin/sh", "-c", "cp -r /tmp/source/* /tmp/destination/"]
        volumeMounts:
          - name: destination
            mountPath: /tmp/destination
          - name: source
            mountPath: /tmp/source/
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      volumes:
        - name: destination
          hostPath:
            path: /destination
            type: DirectoryOrCreate
        - name: source
          persistentVolumeClaim:
            claimName: nginx-data-test
