apiVersion: batch/v1
kind: Job
metadata:
  name: copy-data-to-dest-pvc
spec:
  template:
    spec:
      #securityContext:
        # fsGroup: 1001
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: backup-copy
          #command: ["/bin/sh", "-c", "while true; do echo user $(id -u) group $(id -g) is working; done;"]
        command: ["/bin/sh", "-c", "cp -r /tmp/source/* /tmp/destination/; ls -al /tmp/destination/; chown -R nobody:nogroup /tmp/destination/*"]
        volumeMounts:
          - name: destination
            mountPath: /tmp/destination
          - name: source
            mountPath: /tmp/source/
        securityContext:
          runAsUser: 1001
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: temporary-pvc
        - name: destination
          persistentVolumeClaim:
            claimName: data-sentry-sentry-postgresql-2
