apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-stack-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-nfs-client
  volumeMode: Filesystem
