apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: temporary-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: csi-nfs-client
  volumeMode: Filesystem
